/**
* @file Particle.cpp
 * @brief Implementation of the Particle class
 */

#include "Particle.h"

#include <spdlog/spdlog.h>

#include "../utils/ArrayUtils.h"

Particle::Particle(int type_arg) : x(), v(), m(0) {
  type = type_arg;
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
  owned_index_ = 0;

  // debug-level: particle creation (compiled out by default when LOG_LEVEL=INFO)
  SPDLOG_TRACE("Particle generated (type={})", type);
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  owned_index_ = other.owned_index_;

  // debug-level: particle copy construction
  SPDLOG_DEBUG("Particle generated by copy (type={})", type);
}

Particle::Particle(const std::array<double, 3> &x_arg, const std::array<double, 3> &v_arg, const double m_arg, int type)
    : x(x_arg), v(v_arg), f({0., 0., 0.}), old_f({0., 0., 0.}), m(m_arg), type(type) {
  owned_index_ = 0;
  SPDLOG_DEBUG("Particle generated at position ({}, {}, {})", x[0], x[1], x[2]);
}

Particle::~Particle() {  // debug-level: particle destruction
  SPDLOG_DEBUG("Particle destructed (type={})", type);
}

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(const Particle &other) const {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
         (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, const Particle &p) {
  stream << p.toString();
  return stream;
}
