/**
 * @file Particle.cpp
 * @brief Implementation of the Particle class
 */

#include "Particle.h"

#include <iostream>

#include "utils/ArrayUtils.h"

Particle::Particle(int type_arg) : x(), v(), m(0) {
  type = type_arg;
  std::cout << "Particle generated!" << std::endl;
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  std::cout << "Particle generated by copy!" << std::endl;
}

Particle::Particle(const std::array<double, 3> &x_arg, const std::array<double, 3> &v_arg, const double m_arg, int type)
    : x(x_arg), v(v_arg), f({0., 0., 0.}), old_f({0., 0., 0.}), m(m_arg), type(type) {
  std::cout << "Particle generated!" << std::endl;
}

Particle::~Particle() { std::cout << "Particle destructed!" << std::endl; }

const std::array<double, 3> &Particle::getX() const { return x; }

/**
 * @param newX New position vector
 */
void Particle::setX(const std::array<double, 3> &newX) { x = newX; }

const std::array<double, 3> &Particle::getV() const { return v; }

/**
 * @brief Set the velocity of the particle
 * @param newV New velocity vector
 */
void Particle::setV(const std::array<double, 3> &newV) { v = newV; }

const std::array<double, 3> &Particle::getF() const { return f; }

/**
 * @param newF New force vector
 */
void Particle::setF(const std::array<double, 3> &newF) { f = newF; }

const std::array<double, 3> &Particle::getOldF() const { return old_f; }

/**
 * @param oldF Old force vector
 */
void Particle::setOldF(const std::array<double, 3> &oldF) { old_f = oldF; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(const Particle &other) const {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
         (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, const Particle &p) {
  stream << p.toString();
  return stream;
}